import { exec } from 'child_process';
import { promisify } from 'util';
import dotenv from 'dotenv';
import path from 'path';

// Ensure env is loaded
dotenv.config({ path: path.resolve(__dirname, '../../.env') });

const execAsync = promisify(exec);

// Environment variables — point to FreeSWITCH server
const PBX_HOST = process.env.FREESWITCH_HOST || '192.168.20.140';
const PBX_SSH_USER = process.env.FREESWITCH_SSH_USER || 'iteckadmin';
const PBX_SSH_PASSWORD = process.env.FREESWITCH_SSH_PASSWORD || '';

// Execute SSH command on PBX server
export async function sshExec(command: string): Promise<{ stdout: string; stderr: string }> {
  const sshCmd = `sshpass -p '${PBX_SSH_PASSWORD}' ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 ${PBX_SSH_USER}@${PBX_HOST} "echo '${PBX_SSH_PASSWORD}' | sudo -S ${command}" 2>&1`;
  return execAsync(sshCmd);
}

// Read file from PBX server via SSH (FreeSWITCH config path)
export async function readAsteriskFile(filename: string): Promise<string> {
  try {
    const { stdout } = await sshExec(`cat /usr/local/freeswitch/conf/${filename}`);
    return stdout;
  } catch (error: any) {
    console.error(`Error reading ${filename}:`, error.message);
    throw new Error(`Failed to read ${filename}`);
  }
}

// Write file to PBX server via SSH (FreeSWITCH config path)
export async function writeAsteriskFile(filename: string, content: string): Promise<void> {
  try {
    const tempFile = `/tmp/${filename.replace(/\//g, '_')}.${Date.now()}`;
    const escapedContent = content.replace(/'/g, "'\\''");
    await sshExec(`bash -c 'echo "${escapedContent}" > ${tempFile}'`);
    await sshExec(`cp ${tempFile} /usr/local/freeswitch/conf/${filename}`);
    await sshExec(`chown freeswitch:freeswitch /usr/local/freeswitch/conf/${filename}`);
    await sshExec(`rm ${tempFile}`);
  } catch (error: any) {
    console.error(`Error writing ${filename}:`, error.message);
    throw new Error(`Failed to write ${filename}`);
  }
}

// Reload FreeSWITCH configuration
export async function reloadAsterisk(module?: string): Promise<void> {
  if (module) {
    await sshExec(`fs_cli -x 'reload ${module}'`);
  } else {
    await sshExec("fs_cli -x 'reloadxml'");
  }
}

// Graceful restart FreeSWITCH
export async function restartAsterisk(): Promise<void> {
  await sshExec("fs_cli -x 'fsctl restart graceful'");
}

// Parse PJSIP config into structured JSON
export function parsePjsipConfig(content: string): any {
  const lines = content.split('\n');
  const sections: any[] = [];
  let currentSection: any = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith(';')) continue;

    // Section header: [name] or [name](template) or [name](!)
    const sectionMatch = trimmed.match(/^\[([^\]]+)\](?:\(([^)]+)\))?/);
    if (sectionMatch) {
      if (currentSection) sections.push(currentSection);
      currentSection = {
        name: sectionMatch[1],
        template: sectionMatch[2] || null,
        params: {} as Record<string, string>,
      };
      continue;
    }

    // Key=value pair
    const kvMatch = trimmed.match(/^([^=]+)=(.+)$/);
    if (kvMatch && currentSection) {
      const key = kvMatch[1].trim();
      const value = kvMatch[2].trim();
      currentSection.params[key] = value;
    }
  }

  if (currentSection) sections.push(currentSection);
  return { sections };
}

// Serialize PJSIP config from JSON
export function serializePjsipConfig(config: any): string {
  const lines: string[] = ['; Generated by TAVL PBX Admin', ''];

  for (const section of config.sections) {
    const templatePart = section.template ? `(${section.template})` : '';
    lines.push(`[${section.name}]${templatePart}`);
    for (const [key, value] of Object.entries(section.params)) {
      lines.push(`${key}=${value}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// Parse dialplan config into structured JSON
export function parseDialplanConfig(content: string): any {
  const lines = content.split('\n');
  const contexts: any[] = [];
  let currentContext: any = null;
  let currentExtension: any = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith(';')) continue;

    // Context header: [context-name]
    const contextMatch = trimmed.match(/^\[([^\]]+)\]$/);
    if (contextMatch) {
      if (currentContext) contexts.push(currentContext);
      currentContext = {
        name: contextMatch[1],
        extensions: [] as any[],
        rawContent: '',
      };
      currentExtension = null;
      continue;
    }

    if (!currentContext) continue;

    // Extension: exten => pattern,priority,action
    const extenMatch = trimmed.match(/^exten\s*=>?\s*([^,]+),\s*(\d+|n|s)\s*,\s*(.+)$/i);
    if (extenMatch) {
      const pattern = extenMatch[1].trim();
      const priority = extenMatch[2].trim();
      const action = extenMatch[3].trim();

      if (priority === '1' || !currentExtension || currentExtension.pattern !== pattern) {
        if (currentExtension) currentContext.extensions.push(currentExtension);
        currentExtension = { pattern, priorities: [] };
      }
      currentExtension.priorities.push({ priority, action });
      continue;
    }

    // Same => action (continuation)
    const sameMatch = trimmed.match(/^same\s*=>?\s*(?:n|\d+)\s*,\s*(.+)$/i);
    if (sameMatch && currentExtension) {
      currentExtension.priorities.push({ priority: 'n', action: sameMatch[1].trim() });
    }
  }

  if (currentExtension && currentContext) currentContext.extensions.push(currentExtension);
  if (currentContext) contexts.push(currentContext);

  return { contexts };
}

// Serialize dialplan config from JSON
export function serializeDialplanConfig(config: any): string {
  const lines: string[] = ['; Generated by TAVL PBX Admin', ''];

  for (const context of config.contexts) {
    lines.push(`[${context.name}]`);
    for (const ext of context.extensions) {
      for (let i = 0; i < ext.priorities.length; i++) {
        const p = ext.priorities[i];
        if (i === 0) {
          lines.push(`exten => ${ext.pattern},${p.priority},${p.action}`);
        } else {
          lines.push(` same => ${p.priority},${p.action}`);
        }
      }
    }
    lines.push('');
  }

  return lines.join('\n');
}

// Parse queues config into structured JSON
export function parseQueuesConfig(content: string): any {
  const lines = content.split('\n');
  const queues: any[] = [];
  let currentQueue: any = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith(';')) continue;

    // Queue header: [queue-name]
    const queueMatch = trimmed.match(/^\[([^\]]+)\]$/);
    if (queueMatch) {
      if (currentQueue) queues.push(currentQueue);
      currentQueue = {
        name: queueMatch[1],
        params: {} as Record<string, string>,
        members: [] as string[],
      };
      continue;
    }

    if (!currentQueue) continue;

    // Member => interface
    const memberMatch = trimmed.match(/^member\s*=>?\s*(.+)$/i);
    if (memberMatch) {
      currentQueue.members.push(memberMatch[1].trim());
      continue;
    }

    // Key=value pair
    const kvMatch = trimmed.match(/^([^=]+)=(.+)$/);
    if (kvMatch) {
      const key = kvMatch[1].trim();
      const value = kvMatch[2].trim();
      currentQueue.params[key] = value;
    }
  }

  if (currentQueue) queues.push(currentQueue);
  return { queues };
}

// Serialize queues config from JSON
export function serializeQueuesConfig(config: any): string {
  const lines: string[] = ['; Generated by TAVL PBX Admin', ''];

  for (const queue of config.queues) {
    lines.push(`[${queue.name}]`);
    for (const [key, value] of Object.entries(queue.params)) {
      lines.push(`${key}=${value}`);
    }
    for (const member of queue.members) {
      lines.push(`member => ${member}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// Template name sets for resolving inherited types
const ENDPOINT_TEMPLATES = new Set(['dual-endpoint']);
const AUTH_TEMPLATES = new Set(['auth-template']);
const AOR_TEMPLATES = new Set(['aor-template']);

export function resolveType(section: any, config: any): string {
  if (section.params.type) return section.params.type;
  if (!section.template) return '';
  const tmplName = section.template.replace('!', '').trim();
  if (ENDPOINT_TEMPLATES.has(tmplName)) return 'endpoint';
  if (AUTH_TEMPLATES.has(tmplName)) return 'auth';
  if (AOR_TEMPLATES.has(tmplName)) return 'aor';
  const tmpl = config.sections.find((s: any) => s.name === tmplName);
  return tmpl?.params.type || '';
}

// Extract extensions from PJSIP config
export function extractExtensions(config: any): any[] {
  const extensions: any[] = [];
  const transports = new Set(['transport-udp', 'transport-ws', 'transport-wss']);
  const templateDefs = new Set<string>();

  for (const section of config.sections) {
    if (section.template === '!' || (section.template && section.template.endsWith('!'))) {
      templateDefs.add(section.name);
    }
  }

  for (const section of config.sections) {
    const sType = resolveType(section, config);
    if (sType !== 'endpoint') continue;
    if (transports.has(section.name)) continue;
    if (templateDefs.has(section.name)) continue;
    if (section.name.startsWith('trunk-')) continue;
    if (!/^\d+$/.test(section.name)) continue;

    const authSection = config.sections.find((s: any) =>
      s.name === section.name && resolveType(s, config) === 'auth'
    );

    extensions.push({
      extension: section.name,
      callerid: section.params.callerid || '',
      context: section.params.context || 'internal',
      template: section.template || '',
      auth: {
        username: authSection?.params.username || section.name,
        password: authSection?.params.password || '',
      },
    });
  }

  return extensions;
}

// Extract trunks from PJSIP config
export function extractTrunks(config: any): any[] {
  const trunks: any[] = [];

  for (const section of config.sections) {
    const sType = resolveType(section, config);
    if (sType !== 'endpoint') continue;
    if (!section.name.startsWith('trunk-')) continue;

    const identifySection = config.sections.find((s: any) =>
      (s.params.type === 'identify' || resolveType(s, config) === 'identify') &&
      s.params.endpoint === section.name
    );

    const aorName = section.params.aors;
    const aorSection = config.sections.find((s: any) =>
      s.name === aorName && (s.params.type === 'aor' || resolveType(s, config) === 'aor')
    );

    const match = identifySection?.params.match || '';
    const host = match.replace('/32', '');

    trunks.push({
      name: section.name,
      host: host,
      fromDomain: section.params.from_domain || '',
      context: section.params.context || '',
      allow: section.params.allow || '',
      transport: section.params.transport || 'transport-udp',
      qualifyFrequency: aorSection?.params.qualify_frequency || '60',
    });
  }

  return trunks;
}
